name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      # Wait for each required check to complete
      - name: Wait for check-signature to complete
        uses: peter-evans/wait-for-check@v2
        with:
          check-name: 'check-signature'  # Replace with the actual name of your CI check
          interval: 10
          timeout: 600  # Wait up to 10 minutes (600 seconds)

      - name: Wait for validation check to complete
        uses: peter-evans/wait-for-check@v2
        with:
          check-name: 'validation'  # Replace with the actual name of your build check
          interval: 10
          timeout: 600

      - name: Check if PR is mergeable
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Ensure the PR is mergeable
            if (pr.data.mergeable_state === 'clean' && pr.data.state === 'open') {
              console.log('Merging PR...');
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });
            } else {
              console.log('PR cannot be merged. Mergeable state is not clean.');
            }